export const professionalSignupData = {
  provinceOptions: [
    "Drenthe",
    "Flevoland",
    "Friesland",
    "Gelderland",
    "Groningen",
    "Limburg",
    "North Brabant",
    "North Holland",
    "Overijssel",
    "South Holland",
    "Utrecht",
    "Zeeland",
    "Antwerp",
    "East Flanders",
    "Flemish Brabant",
    "Hainaut",
    "Liège",
    "Limburg (BE)",
    "Luxembourg (BE)",
    "Namur",
    "Walloon Brabant",
    "West Flanders",
    "Brussels-Capital Region",
  ] as const,
  municipalityOptions: [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Groningen",
    "Tilburg",
    "Almere",
    "Breda",
    "Nijmegen",
    "Antwerp",
    "Ghent",
    "Charleroi",
    "Brussels",
    "Liège",
    "Schaerbeek",
    "Anderlecht",
    "Bruges",
    "Namur",
    "Leuven",
  ] as const,
  businessTypeOptions: [
    { value: "salonOwner", label: "Salon Owner" },
    { value: "freelancer", label: "Freelancer" },
    { value: "other", label: "Other" },
  ] as const,
  initialForm: {
    legalName: "",
    cccNumber: "",
    vatNumber: "",
    street: "",
    number: "",
    postalCode: "",
    province: "",
    municipality: "",
    businessType: "",
    website: "",
    instagram: "",
    otherLink: "",
    contactFirstName: "",
    contactLastName: "",
    contactEmail: "",
    password: "",
    confirmPassword: "",
    acceptTerms: false,
  },
} as const;

